Todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todolist_service.urls", namespace="todolist_service")),
]

todolist_service/urls.py
from django.urls import path

from todolist_service.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView, TaskChangeStatusView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/",
         TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/",
         TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/change_stat/",
         TaskChangeStatusView.as_view(),
         name="task-status-change"),
    path("tags/", TagListView.as_view(), name="tags"),
    path("tags/create/", TagCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tags-delete"),
]

app_name = "todolist_service"

todolist_service/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    tag = models.ManyToManyField(Tag, related_name="tasks", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateField()
    is_done = models.BooleanField(default=False)

    class Meta:
        ordering = ["is_done", "-created"]

    def __str__(self):
        return self.content

todolist_service/forms.py
from django import forms

from .models import Tag, Task


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"


class TaskForm(forms.ModelForm):
    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple
    )

    deadline = forms.DateTimeField(
        required=False,
        widget=forms.DateTimeInput(
            attrs={
                "class": "form-control",
                "placeholder": "Select a datetime",
                "type": "datetime-local",
            }
        ),
    )

    class Meta:
        model = Task
        fields = "__all__"

todolist_service/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from todolist_service.forms import TaskForm, TagForm
from todolist_service.models import Task, Tag


class TaskListView(ListView):
    model = Task
    template_name = "todolist/index.html"


class TaskCreateView(CreateView):
    model = Task
    success_url = reverse_lazy("todolist_service:index")
    form_class = TaskForm
    template_name = "todolist/form.html"


class TaskUpdateView(UpdateView):
    model = Task
    success_url = reverse_lazy("todolist_service:index")
    form_class = TaskForm
    template_name = "todolist/form.html"


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("todolist_service:index")
    template_name = "todolist/confirmation.html"


class TaskChangeStatusView(UpdateView):
    model = Task
    fields = []
    template_name = "todolist/form.html"
    success_url = reverse_lazy("todolist_service:index")

    def get_object(self, queryset=None):
        return get_object_or_404(Task, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        task = form.save(commit=False)
        task.is_done = not task.is_done
        task.save()
        return super().form_valid(form)


class TagListView(ListView):
    model = Tag
    template_name = "todolist/tags.html"


class TagCreateView(CreateView):
    model = Task
    success_url = reverse_lazy("todolist_service:tags")
    template_name = "todolist/form.html"
    form_class = TagForm


class TagUpdateView(UpdateView):
    model = Tag
    success_url = reverse_lazy("todolist_service:tags")
    template_name = "todolist/form.html"
    form_class = TagForm


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("todolist_service:tags")
    template_name = "todolist/confirmation.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Blog Service</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}

    </div>
  </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todolist_service:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todolist_service:tags' %}">Tags</a></li>
</ul>

templates/todolist/confirmation.html
{% extends "base.html" %}
{% block content %}
    <h1>Are you sure you want to delete this entity?</h1>
    <p>All entities that are associated with the entity you selected will be also deleted</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" VALUE="Yes, delete" class="btn btn-danger">
    </form>
{% endblock %}

templates/todolist/form.html
{% extends "base.html" %}
{% block content %}
    <h1>{{ object|yesno:"Update,Create" }}</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

templates/todolist/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h1 class="mt-5">Todolist Service Home
    <a href="{% url 'todolist_service:task-create' %}" class="btn btn-primary link-to-page">
        Create
    </a>
  </h1>
  <p>Welcome to the Best Todolist Ever!</p>

  <div class="row mt-5">
    {% for task in task_list %}
    <div class="col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">{{ task.content }}</h5>
          <p class="card-text">Created: {{ task.created }}</p>
          <p class="card-text">Deadline: {{ task.deadline }}</p>
          <p class="card-text">Status:
            {% if task.is_done %}
            <span class="badge badge-success">Done</span>
                <a href="{% url "todolist_service:task-status-change" pk=task.id %}" class="btn btn-danger">Undo</a>
            {% else %}
            <span class="badge badge-danger">Not done</span>
                <a href="{% url "todolist_service:task-status-change" pk=task.id %}" class="btn btn-primary">Complete</a>
            {% endif %}
          </p>
            {% for tag in task.tag.all %}
                <p class="card-text">Tags: {{ tag.name }}</p>
            {% endfor %}
          <a href="{% url "todolist_service:task-update" pk=task.id %}" class="btn btn-primary">Update</a>
          <a href="{% url "todolist_service:task-delete" pk=task.id %}" class="btn btn-danger">Delete</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/todolist/post_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card shadow-lg">
                <div class="card-body">
                    <h1 class="card-title">{{ post.title }}</h1>
                    <p class="card-text">Author: {{ post.owner }}</p>
                    <p class="card-text">{{ post.content }}</p>
                    <p class="card-text">Created: {{ post.created_time }}</p>
                    <a href="{% url 'todolist:post-update' pk=post.pk %}" class="btn btn-primary">Update</a>
                    <a href="{% url 'todolist:post-delete' pk=post.pk %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5">
    <h2>Comments</h2>
    {% include "includes/comments.html" %}
</div>
{% endblock %}

templates/todolist/tags.html
{% extends 'base.html' %}
{% block content %}
  <h2>Tags List <a href="{% url 'todolist_service:tags-create' %}" class="btn btn-primary btn-sm float-right mt-3">Add tag</a></h2>
  {% if tag_list %}
    <table class="table">
      <tr>
        <td><strong>Tag</strong></td>
        <td><strong>Update</strong></td>
        <td><strong>Delete</strong></td>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a href="{% url 'todolist_service:tags-update' tag.id %}" class="btn btn-secondary">UPDATE</a></td>
          <td><a href="{% url 'todolist_service:tags-delete' tag.id %}" class="btn btn-secondary">DELETE</a></td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}